spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taxi?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&tinyInt1isBit=false&useLegacyDatetimeCode=false
    username: root
    password: Cl16895789.
    hikari: # https://github.com/brettwooldridge/HikariCP (uses milliseconds for all time values)
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000
mybatis-plus:
  mapper-locations: classpath*:com/logic/taxi/**/xml/*.xml
  type-aliases-package: com.logic.taxi.entity #实体扫描，多个package用逗号或者分号分隔
  global-config:
    db-config:
      id-type: ID_WORKER  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker),[此时主键推荐bigint]  3:全局唯一ID(uuid)[此时主键推荐varchar]
  configuration:
    jdbc-type-for-null: ''  #配置JdbcTypeForNull 查询后null字段被转换空字符
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句,调试用
    call-setters-on-nulls: true #map类型数据显示空值字段
server:
  port: 8080
