spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    driverClassName: com.mysql.cj.jdbc.Driver
    filters: stat,wall,slf4j
    initialSize: 5
    maxActive: 20
    maxPoolPreparedStatementPerConnectionSize: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 5
    password: Cl16895789.
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/taxi?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false
    username: root
mybatis-plus:
  mapper-locations: classpath*:com/logic/taxi/**/xml/*.xml
  type-aliases-package: com.logic.taxi.entity #实体扫描，多个package用逗号或者分号分隔
  global-config:
    db-config:
      id-type: ID_WORKER  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker),[此时主键推荐bigint]  3:全局唯一ID(uuid)[此时主键推荐varchar]
  configuration:
    jdbc-type-for-null: ''  #配置JdbcTypeForNull 查询后null字段被转换空字符
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #打印sql语句,调试用
    call-setters-on-nulls: true #map类型数据显示空值字段
server:
  port: 8080


